#!/bin/sh
cd ./spec/libsample && make
cd ../../
mkdir -p lib
ln -s ../src lib/gobject
GI_TYPELIB_PATH="$(pwd)/spec/build" LIBRARY_PATH="$(pwd)/spec/build" LD_LIBRARY_PATH="$(pwd)/spec/build" crystal spec $@
rm -rf lib
